---
swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: https://example.com
info:
  title: IkeMurami PoC
  version: '1.0'
paths:
  "/path/malformed/by/ikemurami":
    post:
      tags:
      - ikemurami
      parameters:
      - name: ikemurami
