---
openapi: 3.0.1
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: https://example.com
info:
  title: Afine Api
  version: '1.0'
paths:
  "/path/malformed/by/afine":
    post:
      tags:
      - afine
      parameters:
      - name: afine
