swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: https://example.com/auth
info:
  version: "1.0"
  title: IkeMurami PoC
  description: Test
paths:
  /:
    get:
      responses:
        200:
          description: Successful respons
